# Generated by Django 3.2.6 on 2021-08-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
